<a href="https://colab.research.google.com/github/priyavarsha06/priyavarsha06/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
import numpy as np
my_array = np.zeros((10, 10), dtype=np.int64)
memory_size = my_array.nbytes
print(f"Memory size of the array: {memory_size} bytes")

Memory size of the array: 800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np

Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
import numpy as np
Z = np.array([1, 2, 3, 4, 5])
Z_reversed = Z[::-1]
print(Z_reversed)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
import numpy as np
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
import numpy as np
Z = np.random.rand(3, 3, 3)
print(Z)

[[[0.51795284 0.87437499 0.92902828]
  [0.61716855 0.46671699 0.50701592]
  [0.3155951  0.12443461 0.06769909]]

 [[0.32795536 0.69067992 0.14354841]
  [0.49611373 0.79261889 0.13044481]
  [0.90872335 0.36745231 0.78882775]]

 [[0.82746411 0.66497437 0.8102665 ]
  [0.85000893 0.33936781 0.10087886]
  [0.22465676 0.75689134 0.47672567]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
import numpy as np
Z = np.random.rand(10, 10)
min_value = Z.min()
max_value = Z.max()
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")

Minimum value: 0.002924399987385695
Maximum value: 0.9746789461319634


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np
Z = np.random.rand(30)
mean_value = Z.mean()
print(f"Mean value: {mean_value}")

Mean value: 0.5070128269054128


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np
x = 5
y = 5
Z = np.ones((x, y))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np
Z = np.ones((3, 3))
Z_with_border = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z_with_border)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
import numpy as np
Z = np.zeros((5, 5))
Z[1, 0] = 1
Z[2, 1] = 2
Z[3, 2] = 3
Z[4, 3] = 4

print(Z)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np
arr = np.arange(6*7*8).reshape(6, 7, 8)
print(arr[1, 5, 3])

99


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
tile = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(tile, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

---



---



---



In [ ]:
import numpy as np
Z = np.random.rand(5, 5)
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)

print(Z)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)
print(result)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np
Z = np.arange(10)
Z[(3 < Z) & (Z < 8)] *= -1

print(Z)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [1]:
import numpy as np

def round_away_from_zero(x):

  return np.sign(x) * np.ceil(np.abs(x))
float_array = np.array([-1.2, 3.5, 0.7, -2.8])
rounded_array = round_away_from_zero(float_array)
print(rounded_array)

[-2.  4.  1. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np

def find_common_values(array1, array2):
  return np.intersect1d(array1, array2)
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 5, 6, 7, 8])
common_values = find_common_values(array1, array2)
print(common_values)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import warnings
import numpy as np

warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
true

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [5]:
import datetime
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-12-01
Today: 2024-12-02
Tomorrow: 2024-12-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
import datetime
import calendar

def get_dates_for_month(year, month):
  num_days = calendar.monthrange(year, month)[1]
  return [datetime.date(year, month, day) for day in range(1, num_days + 1)]
dates_july_2016 = get_dates_for_month(2016, 7)
print(dates_july_2016)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [12]:
import numpy as np
def compute_in_place(A, B):
  A += B
  A =-0.5
  A /= 2
  A *= -1
  return A
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
compute_in_place(A, B)
print(A)

[5 7 9]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [13]:
import numpy as np
random_array = np.random.rand(5) * 10
integer_part1 = np.floor(random_array)
integer_part2 = random_array.astype(int)
integer_part3 = np.trunc(random_array)
integer_part4 = np.array([int(x) for x in random_array])


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
import numpy as np

matrix = np.tile(np.arange(5), (5, 1))

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [14]:
import numpy as np

def integer_generator():
  for i in range(10):
    yield i
generator = integer_generator()
array = np.fromiter(generator, dtype=int)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np

vector = np.linspace(0, 1, 11, endpoint=False)[1:]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [15]:
import numpy as np

small_array = np.arange(10)
sum_result = sum(small_array)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
import numpy as np

# Create two random arrays
A = np.random.rand(5)
B = np.random.rand(5)

# Check if they are equal using np.array_equal
are_equal = np.array_equal(A, B)



#### 43. Make an array immutable (read-only) (★★☆)

In [16]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
my_array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [17]:
import numpy as np
cartesian_coords = np.random.rand(10, 2)
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
rho = np.sqrt(x**2 + y**2)  # Radial distance
phi = np.arctan2(y, x)  # Angle (in radians)
polar_coords = np.column_stack((rho, phi))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [19]:
import numpy as np
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [18]:
import numpy as np
n = 10
x, y = np.meshgrid(np.linspace(0, 1, n), np.linspace(0, 1, n))
structured_array = np.zeros((n, n), dtype=[('x', float), ('y', float)])
structured_array['x'] = x
structured_array['y'] = y

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
import numpy as np

def cauchy_matrix(X, Y):
  X = X[:, np.newaxis]
  diff_matrix = X - Y
  diff_matrix[diff_matrix == 0] = np.finfo(diff_matrix.dtype).eps
  cauchy_matrix = 1.0 / diff_matrix
  return cauchy_matrix

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [20]:
import numpy as np
scalar_types = [np.int8, np.int16, np.int32, np.int64,
                np.uint8, np.uint16, np.uint32, np.uint64,
                np.float16, np.float32, np.float64,
                np.complex64, np.complex128]
for dtype in scalar_types:
  print(f"{dtype.__name__}:")
  print(f"  Minimum: {np.iinfo(dtype).min if 'int' in dtype.__name__ else np.finfo(dtype).min}")
  print(f"  Maximum: {np.iinfo(dtype).max if 'int' in dtype.__name__ else np.finfo(dtype).max}")
  print()


int8:
  Minimum: -128
  Maximum: 127

int16:
  Minimum: -32768
  Maximum: 32767

int32:
  Minimum: -2147483648
  Maximum: 2147483647

int64:
  Minimum: -9223372036854775808
  Maximum: 9223372036854775807

uint8:
  Minimum: 0
  Maximum: 255

uint16:
  Minimum: 0
  Maximum: 65535

uint32:
  Minimum: 0
  Maximum: 4294967295

uint64:
  Minimum: 0
  Maximum: 18446744073709551615

float16:
  Minimum: -65504.0
  Maximum: 65504.0

float32:
  Minimum: -3.4028234663852886e+38
  Maximum: 3.4028234663852886e+38

float64:
  Minimum: -1.7976931348623157e+308
  Maximum: 1.7976931348623157e+308

complex64:
  Minimum: -3.4028234663852886e+38
  Maximum: 3.4028234663852886e+38

complex128:
  Minimum: -1.7976931348623157e+308
  Maximum: 1.7976931348623157e+308



#### 49. How to print all the values of an array? (★★☆)

In [21]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [22]:
import numpy as np

def find_closest_value(vector, scalar):
  index = (np.abs(vector - scalar)).argmin()
  return vector[index]
my_vector = np.array([1, 2, 3, 4, 5])
my_scalar = 2.7
closest_value = find_closest_value(my_vector, my_scalar)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np
dtype = [('position', [('x', float), ('y', float)]),
         ('color', [('r', int), ('g', int), ('b', int)
structured_array = np.zeros(10, dtype=dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import numpy as np
coordinates = np.random.rand(100, 2)
x = coordinates[:, 0, np.newaxis]
y = coordinates[:, 1, np.newaxis]
distances = np.sqrt((x - x.T)**2 + (y - y.T)**2)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [25]:
import numpy as np
float_array = np.array([1.2, 3.5, 0.7, 2.8, 9.1], dtype=np.float32)
float_array.astype(np.int32, copy=False)

array([1, 3, 0, 2, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [30]:
import numpy as np

def generate_2d_gaussian_array(shape, center, sigma):
  x, y = np.indices(shape)
  exponent = -((x - center[0])**2 + (y - center[1])**2) / (2 * sigma**2)
  gaussian_array = np.exp(exponent)
  return gaussian_array
shape = (100, 100)
center = (50, 5)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [32]:
import numpy as np

def randomly_place_elements(array, p, element_value=1):
  rows, cols = array.shape
  indices = np.random.choice(rows * cols, size=p, replace=False)
  row_indices = indices // cols
  col_indices = indices % cols
  array[row_indices, col_indices] = element_value
my_array = np.zeros((5, 5))
randomly_place_elements(my_array, 5)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [31]:
import numpy as np
def subtract_row_mean(matrix):
  row_means = np.mean(matrix, axis=1, keepdims=True)
  return matrix - row_means
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
centered_matrix = subtract_row_mean(my_matrix)

#### 59. How to sort an array by the nth column? (★★☆)

In [35]:
import numpy as np

def sort_by_nth_column(array, column_index):
  return array[array[:, column_index].argsort()]
my_array = np.array([[1, 4, 2], [3, 1, 5], [2, 3, 0]])
sorted_array = sort_by_nth_column(my_array, 1)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [34]:
import numpy as np

def has_null_columns(array):
  return (array == 0).all(axis=0).any()
my_array = np.array([[1, 0, 2], [0, 0, 0], [3, 0, 4]])
has_null_cols = has_null_columns(my_array)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [33]:
import numpy as np

def find_nearest_value(array, value):
  index = (np.abs(array - value)).argmin()
  return array[index]
my_array = np.array([1, 2, 3, 4, 5])
my_value = 2.7
nearest_value = find_nearest_value(my_array, my_value)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [38]:
import numpy as np

def sum_with_iterator(array1, array2):
  it1 = np.nditer(array1)
  it2 = np.nditer(array2)
  result = []
  for x, y in zip(it1, it2):
    result.append(x + y)
  return np.array(result).reshape(array1.shape[0], array2.shape[1])
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])
sum_array = sum_with_iterator(array1, array2)

ValueError: cannot reshape array of size 3 into shape (1,1)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)